name: WaterCore
main: com.rdproject.watercore.WaterCore
version: 1.2
api-version: 1.17
author: RDProject
description: Core API for SomePlugins & WaterPlugins (Spigot Version)
website: https://github.com/RDProjectOfficial
commands:
  watercore:
    description: WaterCore Command
    aliases: [api, system, core]
